stages:
  - build
  - package

variables:
  APP_VERSION: $CI_PIPELINE_IID

build web app:
  stage: build
  script:
    - mvn clean install -D skipTests
  artifacts:
    paths:
      - build

build docker image:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$APP_VERSION .
    - docker image ls